### ISSUE TITLE
Error in parcing

### ISSUE THREAD

**Issue by Thesam1798** [traefik/plugin-rewritebody#17]
### Background :
Traefik : latest
Provider : File and Docker
Server's OS: Ubuntu 20.04

**Rewrite configuration :**
```
[http.middlewares]
  [http.middlewares.rewrite-foo.plugin.rewritebody]
    lastModified = false

    [[http.middlewares.rewrite-foo.plugin.rewritebody.rewrites]]
      regex = 'http://'
      replacement = 'https://'
```

**Docker configuration :** 
```
services:
  test:
    container_name: test
    image: thesam1798/liberty:web
    depends_on:
      - reverse-proxy
    volumes:
      - "/srv/docker/www/test:/app"
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.gestion.rule=Host(`XXXXXXXXXXXXX`)"
      - "traefik.http.routers.gestion.entrypoints=websecure"
      - "traefik.http.routers.gestion.tls=true"
      - "traefik.http.routers.gestion.tls.certresolver=sslresolver"

      - "traefik.http.routers.gestion.middlewares=rewrite-foo@file"
      - "traefik.http.middlewares.gestion-middlewares.compress=true"
```

### Describe the bug
Parcing works but not every time

### To Reproduce
**it doesn't work :**
in index.html : 
```
<body class="ini-expand-fea">
	TEST|http://|TEST
</body>

http://
```
**_to make it work remove any character_**

**Screen**

![2021-03-08_12-45](https://user-images.githubusercontent.com/20329547/110320782-20525c80-8011-11eb-9eea-88a9b2a10346.png)
